SELECT A.HOUR, NVL(COUNT, 0) AS COUNT
FROM (
    SELECT LEVEL - 1 AS HOUR
    FROM DUAL
    CONNECT BY LEVEL <= 24
    ) A
LEFT OUTER JOIN ( 
    SELECT HOUR, COUNT(HOUR) AS COUNT
    FROM (
        SELECT EXTRACT(HOUR FROM CAST(DATETIME AS TIMESTAMP)) AS HOUR
        FROM ANIMAL_OUTS
    )
    GROUP BY HOUR
) B
ON A.HOUR = B.HOUR
ORDER BY HOUR

-- outer join 확실히 잡기