SELECT
    ACNO,
    TX_DT,
    TX_SEQ,
    TX_AF_BAL
FROM KKB_ACNO_TX
WHERE (ACNO, TX_DT, TX_SEQ) IN (
    SELECT ACNO, TX_DT, MAX(TX_SEQ) AS TX_SEQ
    FROM KKB_ACNO_TX
    GROUP BY ACNO, TX_DT
)
ORDER BY ACNO, TX_DT

-- 35 / 35